php_memcached.lo: /Users/piotrglaza/Documents/laravel/CRM-X-TEST/memcached-2.2.0/php_memcached.c
	$(LIBTOOL) --mode=compile $(CC) -I/opt/homebrew/Cellar/php@7.3/7.3.33_3/include/php    -I. -I/Users/piotrglaza/Documents/laravel/CRM-X-TEST/memcached-2.2.0 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/piotrglaza/Documents/laravel/CRM-X-TEST/memcached-2.2.0/php_memcached.c -o php_memcached.lo 
php_libmemcached_compat.lo: /Users/piotrglaza/Documents/laravel/CRM-X-TEST/memcached-2.2.0/php_libmemcached_compat.c
	$(LIBTOOL) --mode=compile $(CC) -I/opt/homebrew/Cellar/php@7.3/7.3.33_3/include/php    -I. -I/Users/piotrglaza/Documents/laravel/CRM-X-TEST/memcached-2.2.0 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/piotrglaza/Documents/laravel/CRM-X-TEST/memcached-2.2.0/php_libmemcached_compat.c -o php_libmemcached_compat.lo 
fastlz/fastlz.lo: /Users/piotrglaza/Documents/laravel/CRM-X-TEST/memcached-2.2.0/fastlz/fastlz.c
	$(LIBTOOL) --mode=compile $(CC) -I/opt/homebrew/Cellar/php@7.3/7.3.33_3/include/php    -I. -I/Users/piotrglaza/Documents/laravel/CRM-X-TEST/memcached-2.2.0 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/piotrglaza/Documents/laravel/CRM-X-TEST/memcached-2.2.0/fastlz/fastlz.c -o fastlz/fastlz.lo 
g_fmt.lo: /Users/piotrglaza/Documents/laravel/CRM-X-TEST/memcached-2.2.0/g_fmt.c
	$(LIBTOOL) --mode=compile $(CC) -I/opt/homebrew/Cellar/php@7.3/7.3.33_3/include/php    -I. -I/Users/piotrglaza/Documents/laravel/CRM-X-TEST/memcached-2.2.0 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/piotrglaza/Documents/laravel/CRM-X-TEST/memcached-2.2.0/g_fmt.c -o g_fmt.lo 
php_memcached_session.lo: /Users/piotrglaza/Documents/laravel/CRM-X-TEST/memcached-2.2.0/php_memcached_session.c
	$(LIBTOOL) --mode=compile $(CC) -I/opt/homebrew/Cellar/php@7.3/7.3.33_3/include/php    -I. -I/Users/piotrglaza/Documents/laravel/CRM-X-TEST/memcached-2.2.0 $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /Users/piotrglaza/Documents/laravel/CRM-X-TEST/memcached-2.2.0/php_memcached_session.c -o php_memcached_session.lo 
$(phplibdir)/memcached.la: ./memcached.la
	$(LIBTOOL) --mode=install cp ./memcached.la $(phplibdir)

./memcached.la: $(shared_objects_memcached) $(MEMCACHED_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS)  -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_memcached) $(MEMCACHED_SHARED_LIBADD)

